name: CI

on:
  push:
  pull_request:
#   release:
#     types: [published]

jobs:
  build-mac:
    name: "macOS"
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install xcpretty
      run: |
        sudo gem install xcpretty

    - name: Create Project
      run: |
        cd physx
        ./generate_projects.sh mac64
    - name: Build
      run: |
        cd physx/compiler/mac64
        xcodebuild ARCHS="x86_64 arm64" VALID_ARCHS="x86_64 arm64" ONLY_ACTIVE_ARCH=NO -scheme install -configuration release build | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Show Result
      run: |
        cd physx
        echo "Files in bin/mac.universal/release: "
        ls -l bin/mac.universal/release
        echo "Show lipo info: "
        ls bin/mac.universal/release/*.a | xargs lipo -info

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-universal
        path: physx/bin/mac.universal/release/*.a

  build-ios:
    name: "iOS"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { sdk: iphoneos, arch: arm64, toolchain: OS64 }
          - { sdk: iphonesimulator, arch: x86_64, toolchain: SIMULATOR64 }
          - { sdk: iphonesimulator, arch: arm64, toolchain: SIMULATORARM64 }
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install xcpretty
      run: |
        sudo gem install xcpretty

    - name: Create Project
      run: |
        cd physx
        rm -rf compiler/ios64
        rm -rf bin/ios.arm_64
        ./generate_projects.sh ios64 ${{ matrix.config.toolchain }}

    - name: Build
      run: |
        cd physx/compiler/ios64
        xcodebuild ARCHS="${{ matrix.config.arch }}" VALID_ARCHS="${{ matrix.config.arch }}" ONLY_ACTIVE_ARCH=NO -sdk ${{ matrix.config.sdk }} -scheme install -configuration release build | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Show Result
      run: |
        cd physx
        echo "Files in bin/ios.arm_64/release: "
        ls -l bin/ios.arm_64/release
        echo "Show lipo info: "
        ls bin/ios.arm_64/release/*.a | xargs lipo -info

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-${{ matrix.config.sdk }}-${{ matrix.config.arch }}
        path: physx/bin/ios.arm_64/release/*.a

  create-fat-library:
    name: "Create iOS Fat Library"
    runs-on: macos-latest
    needs: build-ios
    steps:
    - name: Download iOS Artifacts (ios-iphoneos-arm64)
      uses: actions/download-artifact@v4
      with:
        name: ios-iphoneos-arm64
        path: artifacts/ios-iphoneos-arm64

    - name: Download iOS Artifacts (ios-iphonesimulator-x86_64)
      uses: actions/download-artifact@v4
      with:
        name: ios-iphonesimulator-x86_64
        path: artifacts/ios-iphonesimulator-x86_64

    - name: Create Fat Library
      run: |
        dir1="artifacts/ios-iphoneos-arm64"
        dir2="artifacts/ios-iphonesimulator-x86_64"
        output_dir="artifacts/ios-fat"

        mkdir -p "$output_dir"

        for file in "$dir1"/*.a; do
          filename=$(basename "$file")
          if [[ -f "$dir2/$filename" ]]; then
              lipo -create "$file" "$dir2/$filename" -output "$output_dir/$filename"
              echo "Created fat library: $output_dir/$filename"
          else
              echo "Skipping $filename: No matching file in $dir2"
          fi
        done

    - name: Upload Fat Library
      uses: actions/upload-artifact@v4
      with:
        name: ios-fat
        path: artifacts/ios-fat
