name: CI

on:
  push:
  pull_request:
#   release:
#     types: [published]

jobs:
  build-mac:
    name: "macOS"
    runs-on: macos-latest
    steps:
    - name: Show CMake Version
      run: |
        which cmake
        cmake --version

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install xcpretty
      run: |
        sudo gem install xcpretty

    - name: Create Project
      run: |
        cd physx
        ./generate_projects.sh mac64
    - name: Build
      run: |
        cd physx/compiler/mac64
        xcodebuild ARCHS="x86_64 arm64" VALID_ARCHS="x86_64 arm64" ONLY_ACTIVE_ARCH=NO -scheme install -configuration release build | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Show Result
      run: |
        cd physx
        echo "Files in bin/mac.universal/release: "
        ls -l bin/mac.universal/release
        echo "Show lipo info: "
        ls bin/mac.universal/release/*.a | xargs lipo -info

    - name: Check minos Version
      run: |
        echo "Check LC_VERSION_MIN_MACOSX ..."
        otool -l ./physx/bin/mac.universal/release/libPhysX_static_64.a | grep -A5 -B1 -m1 "LC_VERSION_MIN_MACOSX" || true
        echo "Check LC_BUILD_VERSION ..."
        otool -l ./physx/bin/mac.universal/release/libPhysX_static_64.a | grep -A5 -B1 -m1 "LC_BUILD_VERSION" || true

    - name: Upload Artifact (.a)
      uses: actions/upload-artifact@v4
      with:
        name: mac-universal
        path: physx/bin/mac.universal/release/*.a

    - name: Upload Artifact (.h)
      uses: actions/upload-artifact@v4
      with:
        name: cpp-header
        path: physx/install/mac64/*

  build-ios:
    name: "iOS"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { sdk: iphoneos, arch: arm64, toolchain: OS64 }
          - { sdk: iphonesimulator, arch: x86_64, toolchain: SIMULATOR64 }
          - { sdk: iphonesimulator, arch: arm64, toolchain: SIMULATORARM64 }
    steps:
    - name: Show CMake Version
      run: |
        which cmake
        cmake --version
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install xcpretty
      run: |
        sudo gem install xcpretty

    - name: Create Project
      run: |
        cd physx
        ./generate_projects.sh ios64 ${{ matrix.config.toolchain }}

    - name: Build
      run: |
        cd physx/compiler/ios64
        xcodebuild ARCHS="${{ matrix.config.arch }}" VALID_ARCHS="${{ matrix.config.arch }}" ONLY_ACTIVE_ARCH=NO -sdk ${{ matrix.config.sdk }} -scheme install -configuration release build | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Show Result
      run: |
        cd physx
        echo "Files in bin/ios.arm_64/release: "
        ls -l bin/ios.arm_64/release
        echo "Show lipo info: "
        ls bin/ios.arm_64/release/*.a | xargs lipo -info
    
    - name: Check minos Version
      run: |
        echo "Check LC_VERSION_MIN_IPHONEOS ..."
        otool -l ./physx/bin/ios.arm_64/release/libPhysX_static_64.a | grep -A5 -B1 -m1 "LC_VERSION_MIN_IPHONEOS" || true
        echo "Check LC_BUILD_VERSION ..."
        otool -l ./physx/bin/ios.arm_64/release/libPhysX_static_64.a | grep -A5 -B1 -m1 "LC_BUILD_VERSION" || true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-${{ matrix.config.sdk }}-${{ matrix.config.arch }}
        path: physx/bin/ios.arm_64/release/*.a

  create-fat-library:
    name: "Create iOS Fat Library"
    runs-on: macos-latest
    needs: build-ios
    steps:
    - name: Download iOS Artifacts (ios-iphoneos-arm64)
      uses: actions/download-artifact@v4
      with:
        name: ios-iphoneos-arm64
        path: artifacts/ios-iphoneos-arm64

    - name: Download iOS Artifacts (ios-iphonesimulator-x86_64)
      uses: actions/download-artifact@v4
      with:
        name: ios-iphonesimulator-x86_64
        path: artifacts/ios-iphonesimulator-x86_64

    - name: Create Fat Library
      run: |
        dir1="artifacts/ios-iphoneos-arm64"
        dir2="artifacts/ios-iphonesimulator-x86_64"
        output_dir="artifacts/ios-fat"

        mkdir -p "$output_dir"

        for file in "$dir1"/*.a; do
          filename=$(basename "$file")
          if [[ -f "$dir2/$filename" ]]; then
              lipo -create "$file" "$dir2/$filename" -output "$output_dir/$filename"
              echo "Created fat library: $output_dir/$filename"
          else
              echo "Skipping $filename: No matching file in $dir2"
          fi
        done

    - name: Upload Fat Library
      uses: actions/upload-artifact@v4
      with:
        name: ios-fat
        path: artifacts/ios-fat

    - uses: geekyeggo/delete-artifact@v5
      with:
        name: ios-iphoneos-arm64

    - uses: geekyeggo/delete-artifact@v5
      with:
        name: ios-iphonesimulator-x86_64

  build-android:
    name: "android"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: armeabi-v7a }
          - { arch: arm64-v8a }
          - { arch: x86 }
          - { arch: x86_64 }

    steps:
    - name: Show CMake Version
      run: |
        which cmake
        cmake --version
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        local-cache: true

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Project
      run: |
        export PM_AndroidNDK_PATH=${{ steps.setup-ndk.outputs.ndk-path }}
        cd physx
        ./generate_projects.sh android-${{ matrix.config.arch }}
  
    - name: Build
      run: |
        cd physx/compiler/android-${{ matrix.config.arch }}-release
        cpu_count=$(nproc)
        VERBOSE=1 make -j${cpu_count}

    - name: Show Result
      run: |
        cd physx
        echo "Files in bin/android.${{ matrix.config.arch }}.fp-soft/release: "
        ls -l bin/android.${{ matrix.config.arch }}.fp-soft/release

    - name: Upload Artifact (.a)
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.config.arch }}
        path: physx/bin/android.${{ matrix.config.arch }}.fp-soft/release/*.a


  build-openharmony:
    name: "openharmony"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: armeabi-v7a }
          - { arch: arm64-v8a }
          - { arch: x86_64 }

    steps:
    - name: Show CMake Version
      run: |
        which cmake
        cmake --version
    - name: Get oh sdk cache directory path
      id: oh-sdk-cache-dir-path
      run: |
        echo "cache dir: "
        echo "dir=$HOME/openharmony" >> $GITHUB_OUTPUT

    - name: Output cache dir
      run: |
        echo "Output cache dir: ${{ steps.oh-sdk-cache-dir-path.outputs.dir }}"

    - name: Cache OH SDK
      id: cache-oh-sdk
      uses: actions/cache@v4
      env:
        cache-name: cache-oh-sdk-13
      with:
        path: ${{ steps.oh-sdk-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: No Cache found, install oh sdk
      if: ${{ steps.cache-oh-sdk.outputs.cache-hit != 'true' }}
      continue-on-error: false
      run: |
        if [ ! -d "$HOME/openharmony" ]; then
        mkdir -p $HOME/openharmony
        echo "Download commandline-tools-linux-x64-5.0.7.200.zip ..."
        wget -q https://github.com/dumganhar/oh-sdk-for-ci/releases/download/api-13/commandline-tools-linux-x64-5.0.7.200.zip.001
        wget -q https://github.com/dumganhar/oh-sdk-for-ci/releases/download/api-13/commandline-tools-linux-x64-5.0.7.200.zip.002
        echo "Unzip commandline-tools-linux-x64-5.0.7.200.zip ..."
        7z x commandline-tools-linux-x64-5.0.7.200.zip.001 -o$HOME/openharmony > /dev/null
        cd $HOME/openharmony
        ls -l
        cd commandline-tools-linux-x64-5.0.7.200
        ls -l
        fi

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Project
      run: |
        export PM_OpenHarmonyNDK_PATH=$HOME/openharmony/commandline-tools-linux-x64-5.0.7.200/sdk/default/openharmony/native
        cd physx
        ./generate_projects.sh openharmony-${{ matrix.config.arch }}
  
    - name: Build
      run: |
        export PATH=$HOME/openharmony/commandline-tools-linux-x64-5.0.7.200/sdk/default/openharmony/native/build-tools/cmake/bin:$PATH
        cd physx/compiler/openharmony-${{ matrix.config.arch }}-release
        ninja

    - name: Show Result
      run: |
        cd physx
        echo "Files in bin/openharmony.${{ matrix.config.arch }}.fp-soft/release: "
        ls -l bin/openharmony.${{ matrix.config.arch }}/release

    - name: Upload Artifact (.a)
      uses: actions/upload-artifact@v4
      with:
        name: openharmony-${{ matrix.config.arch }}
        path: physx/bin/openharmony.${{ matrix.config.arch }}.fp-soft/release/*.a