name: Compile Emscripten Library

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [published]

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile:
    if:
      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
    name: "Emscripten"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup emsdk
        uses: dumganhar/setup-emsdk@997d2cde2deabda085a11f98e86e842915b0e846
        with:
          version: 3.1.41
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: |
          which emcc
          emcc -v
          which emcmake
          which emmake

      - name: Install ninja
        run: |
          if ! command -v ninja &> /dev/null; then
              echo "Ninja not found, installing..."
              # sudo apt update
              sudo apt install ninja-build
          else
              echo "Ninja is already installed."
          fi
          which ninja

      - name: Compile
        run: |
          export EMSCRIPTEN=${EMSDK}/upstream/emscripten
          ./build-emscripten.sh
          echo "============== Compile Successfully! =============="

      - name: Upload Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with: 
          name: physx-fat
          path: builds

      - name: Pack dist files
        if: github.event_name == 'release'
        uses: thedoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        with:
          type: 'zip'
          directory: 'builds'
          path: '.'
          filename: 'physx-fat.zip'

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/physx-fat.zip
          asset_name: physx-fat.zip
          tag: ${{ github.ref }}
